---
ldap_url: ""
ldap_bind_dn: ""
ldap_insecure: false
openshift_api_url: "{{ lookup('ansible.builtin.env', 'openshift_api_url') }}"
openshift_token: "{{ lookup('ansible.builtin.env', 'openshift_token_id') }}"
validate_certificates: "{{ lookup('ansible.builtin.env', 'validate_certificates') | default('false') | bool }}"
