# yamllint disable
{{- if not (eq .Values.kueue "Removed") }}
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Kueue.v1.kueue.openshift.io
    argocd.argoproj.io/sync-wave: "2"
  name: openshift-kueue-operator-group
  namespace: openshift-kueue-operator
spec: {}
{{- end }}
# yamllint enable
