# yamllint disable
{{- with .Values.operatorReplicas }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: rhods-operator
  namespace: redhat-ods-operator
spec:
  replicas: {{ . }}
{{- end }}
# yamllint enable
