---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: intersight-operator-group
  namespace: intersight-operator
spec:
  targetNamespaces:
    - intersight-operator
