---
# OpenShift deployment and configuration
- name: Deploy and Configure OpenShift for AI Pod
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: "{{ (lookup('ansible.builtin.env', 'VIRTUAL_ENV') + '/bin/python3') if lookup('ansible.builtin.env', 'VIRTUAL_ENV') else 'python3' }}"
    host_vars_dir: "{{ host_vars_dir | default(playbook_dir ~ '/../host_vars') }}"

  pre_tasks:
    - name: Find Variable Files Under host_vars
      ansible.builtin.find:
        paths: "{{ host_vars_dir }}/openshift"
        patterns:
          - "*.ezai.yaml"
        file_type: file
      register: openshift_var_files
      tags: always

    - name: Merge Variable Files Into a Single Dictionary
      ansible.builtin.set_fact:
        merged_vars: "{{ merged_vars | default({}) | combine((lookup('ansible.builtin.file', item.path) | from_yaml), recursive=True) }}"
      loop: "{{ openshift_var_files.files | sort(attribute='path') }}"
      loop_control:
        label: "{{ item.path | basename }}"
      tags: always

    - name: Set Merged OpenShift Object
      ansible.builtin.set_fact:
        openshift: "{{ merged_vars.openshift | default({}) }}"
      tags: always

  roles:
    # # - role: cisco.ai_pods.openshift_install
    # - role: openshift_install
    #   tags: [install]

    # - role: cisco.ai_pods.openshift_certificates
    - role: openshift_certificates
      tags: [certificates]
      when: openshift.certificates is defined and openshift.certificates.api_key_file | length > 0

    # - role: cisco.ai_pods.openshift_auth
    - role: openshift_auth
      tags: [auth]
      when: openshift.ldap is defined and openshift.ldap.url | length > 0

    - role: openshift_gitea
      tags: [gitea]
      when: openshift.operators.gitea.enabled | default(false) | bool

    - role: openshift_argo_cd
      tags: [argocd]
      when: openshift.operators.openshift_gitops.enabled | default(false) | bool

    # - role: cisco.ai_pods.openshift_gitops
    - role: openshift_gitops
      tags: [gitops]
      when: openshift.operators.openshift_gitops.enabled | default(false) | bool

    # - role: cisco.ai_pods.gpu_operators
    #   tags: [gpu]
