---
# Observability stack deployment
- name: Deploy Splunk Observability for AI Pod
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    host_vars_dir: "{{ host_vars_dir | default(playbook_dir ~ '/../host_vars') }}"

  pre_tasks:
    - name: Find Variable Files Under host_vars
      ansible.builtin.find:
        paths: "{{ host_vars_dir }}/splunk_observability"
        patterns:
          - "*.ezai.yaml"
        file_type: file
      register: splunk_observability_var_files

    - name: Merge Variable Files Into a Single Dictionary
      ansible.builtin.set_fact:
        merged_vars: "{{ merged_vars | default({}) | combine((lookup('ansible.builtin.file', item.path) | from_yaml), recursive=True) }}"
      loop: "{{ splunk_observability_var_files.files | sort(attribute='path') }}"
      loop_control:
        label: "{{ item.path | basename }}"

    - name: Set Merged Splunk Observability Object
      ansible.builtin.set_fact:
        splunk_observability: "{{ merged_vars.splunk_observability | default({}) }}"

  roles:
    # - role: cisco.ai_pods.splunk_observability
    - role: splunk_observability
      when:
        - splunk_observability.access_token is defined
        - splunk_observability.openshift_cluster is defined
        - splunk_observability.otel_collector is defined
        - splunk_observability.splunk_platform is defined
