---
name: Run collection certification checks

permissions:
  contents: read

env:
  ORIGIN_PYTHON_VERSION: "3.12"
  ANSIBLE_CORE_VERSION: "2.16.0"
  GALAXY_IMPORTER_VERSION: "0.4.31"

'on':
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: cert-ver-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-import:
    name: Build and import collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.ORIGIN_PYTHON_VERSION }}

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install "ansible-core==${ANSIBLE_CORE_VERSION}" "galaxy-importer==${GALAXY_IMPORTER_VERSION}"

      - name: Build tarball and run galaxy-importer
        run: python -m galaxy_importer.main --git-clone-path . --output-path /tmp

  sanity:
    name: Sanity (${{ matrix.ansible }}, Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible: [stable-2.16]
        python: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@d3a8ec7a59694e25e210fcd44738910149537f0e # v1.17.0
        with:
          ansible-core-version: ${{ matrix.ansible }}
          origin-python-version: ${{ env.ORIGIN_PYTHON_VERSION }}
          testing-type: sanity
          target-python-version: ${{ matrix.python }}
          collection-root: .
          pull-request-change-detection: false
