---
name: CI

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

'on':
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    env:
      LINT_VER: 24.12.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install ansible-lint
        run: |
          python -m pip install --upgrade pip
          python -m pip install "ansible-lint==${LINT_VER}"

      - name: Run ansible-lint
        run: ansible-lint --profile=production --skip-list sanity .
  all_green:
    if: ${{ always() }}
    needs:
      - ansible-lint
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert '${{ needs.ansible-lint.result }}' == 'success'"
