---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sriov-network-operator
  namespace: openshift-sriov-network-operator
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  targetNamespaces:
    - openshift-sriov-network-operator
